
// Generated by https://quicktype.io

export interface ResponseExerciseByRanges {
    message: string;
    data:    ExerciseByDateRange[];
}

export interface ExerciseByDateRange {
    weight:       number;
    reps:         number;
    exerciseName: string;
    image?:       string;
}
