
// Generated by https://quicktype.io

export interface ResponseTopTenExercises {
    message: string;
    data:    TopTenExercisesData[];
}

export interface TopTenExercisesData {
    weight:       number;
    reps:         number;
    exerciseName: string;
}
