
// Generated by https://quicktype.io

export interface ResponseLogin {
    message: string;
    data:    string;
}

// Generated by https://quicktype.io

export interface ErrorResponse {
    message:    string;
    error:      string;
    statusCode: number;
}
