
// Generated by https://quicktype.io

export interface Categories {
    message: string;
    data:    MuscleProps[];
}

export interface MuscleProps{
    _id: string;
    name: string;
    isDefault: boolean;
    bgColor?: string;
    imageUrl?: string;
    textColor?: string;
    gridClass?: string;
}

export interface CardMuscleGroupProps{
    group: MuscleProps;
    className?: string;
    onClick: () => void;

}

export interface MuscleGroupExercisesProps{
    onSelectGroup: (name: string) => void
}
