// Generated by https://quicktype.io

export interface ResponseExercises {
    message: string;
    data:    Exercise[];
}

export interface Exercise {
    _id:       string;
    name:      string;
    isDefault: boolean;
    category:  string;
    image?:    string;
}
